// <auto-generated />
using System;
using ConferenceBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenceBooking.Data.Postgresql.Migrations
{
    [DbContext(typeof(ConferenceBookingDbContext))]
    [Migration("20260907223018_InitialBookingSchema")]
    partial class InitialBookingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenceBooking.Data.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_hourly_rate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<decimal>("RentalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("rental_cost");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("room_name");

                    b.Property<decimal>("ServicesCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("services_cost");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_cost");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "StartsAt")
                        .HasDatabaseName("ix_bookings_room_id_starts_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_bookings_user_id_created_at");

                    b.ToTable("bookings", "public", t =>
                        {
                            t.HasCheckConstraint("ck_bookings_base_hourly_rate", "base_hourly_rate > 0");

                            t.HasCheckConstraint("ck_bookings_costs", "rental_cost >= 0 AND services_cost >= 0 AND total_cost = rental_cost + services_cost");

                            t.HasCheckConstraint("ck_bookings_interval", "ends_at > starts_at");

                            t.HasCheckConstraint("ck_bookings_room_name", "length(btrim(room_name)) > 0");

                            t.HasCheckConstraint("ck_bookings_user_id", "length(btrim(user_id)) > 0");
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Data.Entities.BookingServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_services_booking_id_service_id");

                    b.ToTable("booking_services", "public", t =>
                        {
                            t.HasCheckConstraint("ck_booking_services_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_booking_services_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Data.Entities.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_hourly_rate");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Capacity", "Id")
                        .HasDatabaseName("ix_rooms_capacity_id")
                        .HasFilter("NOT is_deleted");

                    b.ToTable("rooms", "public", t =>
                        {
                            t.HasCheckConstraint("ck_rooms_base_hourly_rate", "base_hourly_rate > 0");

                            t.HasCheckConstraint("ck_rooms_capacity", "capacity > 0");

                            t.HasCheckConstraint("ck_rooms_name", "length(btrim(name)) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BaseHourlyRate = 2000m,
                            Capacity = 50,
                            IsDeleted = false,
                            Name = "Зал А",
                            Version = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            BaseHourlyRate = 3500m,
                            Capacity = 100,
                            IsDeleted = false,
                            Name = "Зал B",
                            Version = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            BaseHourlyRate = 1500m,
                            Capacity = 30,
                            IsDeleted = false,
                            Name = "Зал C",
                            Version = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Data.Entities.RoomServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("room_services", "public", t =>
                        {
                            t.HasCheckConstraint("ck_room_services_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_room_services_price", "price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Name = "Проєктор",
                            Price = 500m,
                            RoomId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Name = "Wi-Fi",
                            Price = 300m,
                            RoomId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Name = "Звук",
                            Price = 700m,
                            RoomId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            Name = "Проєктор",
                            Price = 500m,
                            RoomId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            Name = "Wi-Fi",
                            Price = 300m,
                            RoomId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            Name = "Звук",
                            Price = 700m,
                            RoomId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000031"),
                            Name = "Проєктор",
                            Price = 500m,
                            RoomId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000032"),
                            Name = "Wi-Fi",
                            Price = 300m,
                            RoomId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000033"),
                            Name = "Звук",
                            Price = 700m,
                            RoomId = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Data.Entities.BookingEntity", b =>
                {
                    b.HasOne("ConferenceBooking.Data.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConferenceBooking.Data.Entities.BookingServiceEntity", b =>
                {
                    b.HasOne("ConferenceBooking.Data.Entities.BookingEntity", "Booking")
                        .WithMany("Services")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ConferenceBooking.Data.Entities.RoomServiceEntity", b =>
                {
                    b.HasOne("ConferenceBooking.Data.Entities.RoomEntity", "Room")
                        .WithMany("Services")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConferenceBooking.Data.Entities.BookingEntity", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("ConferenceBooking.Data.Entities.RoomEntity", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
