<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AssemblyName>ConferenceBooking.Core.Application.Tests</AssemblyName>
    <RootNamespace>ConferenceBooking.Core.Application.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.v3" Version="3.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" PrivateAssets="all" />
    <ProjectReference Include="../../../src/Core/Application/Application.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
